// Code generated by tygo. DO NOT EDIT.

//////////
// source: models.go

/**
 * TVAsset represents a single financial asset retrieved from the TradingView screener.
 * It contains raw float64 values for precise calculations and fundamental metrics.
 */
export interface TVAsset {
  /**
   * --- 1. Overview & Base Identity ---
   */
  ticker: string; // Ticker symbol (e.g., "BBCA")
  sector: string; // Sector classification (e.g., "Finance")
  market: string; // Exchange market (e.g., "indonesia")
  fundamental_currency_code: string; // The currency code (e.g., "IDR")
  description: string; // Company name
  price: Money; // Current close price
  change: RawNum; // Price change value
  volume: RawNum; // Trading volume
  relative_volume_10d: Ratio; // Relative volume compared to 10-day average
  market_cap: Money; // Basic market capitalization
  free_float_qty: RawNum; // Free Float (in qty)
  free_float_percentage: Percent; // Free Float percentage
  /**
   * --- 2. Valuation ---
   */
  pe_ratio: Ratio; // Price to Earnings (TTM)
  peg_ratio: Ratio; // PEG Ratio (TTM) - PEG < 1 means undervalued
  ps_ratio: Ratio; // Price to Sales (Current)
  pbv: Ratio; // Price to Book Value (FQ)
  price_to_cash: Ratio; // Price to Cash Ratio
  price_to_fcf: Ratio; // Price to Free Cash Flow (TTM)
  enterprise_value: Money; // Enterprise Value (Current)
  ev_ebitda: Ratio; // Enterprise Value / EBITDA (TTM)
  ev_to_revenue: Ratio; // Enterprise Value to Revenue (TTM)
  ev_to_ebit: Ratio; // Enterprise Value to EBIT (TTM)
  /**
   * --- 3. Profitability ---
   */
  gross_margin: Percent; // Gross Margin (TTM)
  operating_margin: Percent; // Operating Margin (TTM)
  pre_tax_margin: Percent; // Pre-Tax Margin (TTM)
  net_margin: Percent; // Net Margin (TTM)
  fcf_margin: Percent; // Free Cash Flow Margin (TTM)
  roa: Percent; // Return on Assets (FQ)
  roe: Percent; // Return on Equity (FQ)
  roic: Percent; // Return on Invested Capital (FQ)
  /**
   * --- 4. Income Statement ---
   */
  total_revenue: Money; // Total Revenue (TTM)
  revenue_growth: Percent; // Total Revenue YoY Growth (TTM)
  gross_profit: Money; // Gross Profit (TTM)
  operating_income: Money; // Operating Income (TTM)
  net_income: Money; // Net Income (TTM)
  ebitda: Money; // EBITDA (TTM)
  eps: Money; // Earnings Per Share Diluted (TTM)
  eps_growth: Percent; // EPS Diluted YoY Growth (TTM)
  fiscal_period: string; // Example: "2026-Q1"
  fiscal_period_end: Epoch; // Fiscal end date (unix timestamp)
  /**
   * --- 5. Balance Sheet ---
   */
  total_assets: Money; // Total Assets (FQ)
  total_current_assets: Money; // Total Current Assets (FQ)
  cash_and_short_term_invest: Money; // Cash & Short Term Investments (FQ)
  total_liabilities: Money; // Total Liabilities (FQ)
  total_debt: Money; // Total Debt (FQ)
  net_debt: Money; // Net Debt (FQ)
  total_equity: Money; // Total Equity (FQ)
  current_ratio: Ratio; // Current Ratio (FQ) - Current Assets vs Current Debt
  quick_ratio: Ratio; // Quick Ratio (FQ) - Strict liquidity metric
  de_ratio: Ratio; // Debt to Equity Ratio (FQ)
  cash_to_total_debt: Ratio; // Cash to Total Debt Ratio (FQ)
  /**
   * --- 6. Cashflow ---
   */
  operating_cashflow: Money; // Cash from Operating Activities (TTM)
  investing_cashflow: Money; // Cash from Investing Activities (TTM)
  financing_cashflow: Money; // Cash from Financing Activities (TTM)
  free_cashflow: Money; // Free Cash Flow (TTM)
  capital_expenditures: Money; // Capital Expenditures (TTM)
  /**
   * --- 7. Dividends ---
   */
  current_dividend_yield: Percent; // Current Dividend Yield
  dividend_payout_ratio: Percent; // Dividend Payout Ratio (TTM)
  dps: Money; // Dividends Per Share (FY)
  dps_yoy_growth: Percent; // Dividends Per Share YoY Growth (FY)
  /**
   * --- 8. Technicals & Momentum ---
   */
  rsi: RawNum; // Relative Strength Index (14)
  momentum: RawNum; // Momentum indicator
  awesome_oscillator: RawNum; // Awesome Oscillator
  cci20: RawNum; // Commodity Channel Index (20)
  stoch_k: RawNum; // Stochastic %K
  stoch_d: RawNum; // Stochastic %D
  tech_rating_1d: RawNum; // AI Tech Rating 1D (-1 Strong Sell to 1 Strong Buy)
}
export type Percent = number /* float64 */;
export type Ratio = number /* float64 */;
export type Money = number /* float64 */;
export type RawNum = number /* float64 */;
export type Epoch = number /* int64 */;

//////////
// source: payload.go

/**
 * M is a convenience type for map[string]interface{}
 */
export type M = { [key: string]: any};
